### ISSUE TITLE
Eισαγωγή εικόνας

### ISSUE THREAD

**Issue by VaggelisKa** [pibook/_gallery#1]
Καλησπέρα,

Πως ακριβώς θα είσαγω εικόνα στο δικό μου forked repo, διότι ειναι submodule και με πετάει στο repo του site.

**Comment by epidrome** [comment]
https://courses-ionio.github.io/projects/social/

> στοσελίδα χρησιμοποιεί την τεχνολογία git submodules η οποία απαιτεί επιπλέον βήματα για τον συντονισμό των επιμέρους φακέλων, διαβάστε σχετικά

https://github.blog/2016-02-01-working-with-submodules/
