### ISSUE TITLE
Συμμετοχικό περιεχόμενο

### ISSUE THREAD

**Issue by TaniaStoupi** [pibook/_gallery#5]
Σχετικά με το συμμετοχικό περιεχόμενο. Διάβασα τις οδηγίες έχω κάνει τα submodule και έχω ανεβάσει τις φωτογραφίες που ζητούσε, αλλά δεν μπορώ να καταλάβω με ποιον τρόπο πρέπει να περάσω αυτά στο gallery.
Έχω γράψει αυτό: 
---
author: TaniaStoupi
title: the-first-touch-screen
year: 1965
image_url:  _images/the-first-touch-screen.jpg 
caption: 'Η πρώτη οθόνη αφής σε υπολογιστή εφευρέθηκε από τον E.A.Jonshon το 1965, χρησιμοποιούσε ένα μηχανικό σύστημα το οποίο χρησιμοποιούν πολλά smarthphone σήμερα  . Το 1970 ο Dr. G. Samuel Hurst ανακαλύπτει την πρώτη ανθεκτική οθόνη αφής, σχεδόν από ατύχημα. Το 1971 κυκλοφόρησε ο PLATO IV ο οποίος ήταν ο πρώτος υπολογιστής ο οποίος χρησιμοποιήθηκε σε τάξη και έδινε την δυνατότητα στα παιδιά να απαντάνε σε ερωτήσεις "πατώντας" την οθόνη του υπολογιστή.'
license_url: 'https://arstechnica.com/gadgets/2013/04/from-touch-displays-to-the-surface-a-brief-history-of-touchscreen-technology'
license_text: Florence Ion
categories:
  - Εργαλεία
tags:
  - Plato iv 
---

Αλλά μου το εμφανίζει ως απλό κείμενο κάθε φορά που το κάνω commit, ενώ τα άλλα αρχεία που ήδη υπάρχουν τα εμφανίζει με διαφορετικό τρόπο και όχι σαν απλά κείμενα. Δεν μπορώ να καταλάβω τι έχω κάνει λάθος και με ποιόν τρόπο πρέπει να τα γράψω. Θα μπορούσατε να με βοηθήσετε;

**Comment by epidrome** [comment]
@TaniaStoupi 
αν θες άνοιξε θέμα στο δικό σου αποθετήριο και κάλεσε εκεί τον @c15pati

https://github.com/TaniaStoupi/site
μια πρώτη ιδέα στο αποθετήριο σου το γκάλερι οδηγεί στο δικό μου και όχι στο δικό σου αντίγραφο που είναι το σωστό

επομένως το πρόβλημα είναι ρυθμίσεις και η κατανόηση του σαμπμοντουλ και όχι η εικόνα που προσθέτεις

το θέμα εδώ κλείνει γιατί δεν σχετίζεται με πρόβλημα αυτού του αποθετηρίου οπότε δεν μπορεί να λυθεί εδώ
